Repository sopra-fs22-group-36/screw-your-neighbor-react, pull requests merged in 2022-05, with the labels that each got.

#73 Feature card playing animation
  src/components/ui/CardComponent.scss
  src/components/ui/CardComponent.tsx
  src/components/views/game/game/gametable/GameTable.tsx
  src/components/views/game/game/yourhand/YourHand.tsx
  src/hooks/api/useCurrentGame.ts
  src/stores/CurrentGameStore.ts
Labels: task

#86 Enhancement only show rooms in finding players
  src/components/views/lobby/Lobby.tsx
Labels: enhancement, task, frontend

#100 disable the number on the announcing board/modal
  src/components/views/game/game/scoreannouncing/AnnouncementModal.tsx
  src/hooks/api/useCurrentGame.ts
  src/stores/CurrentGameStore.ts
Labels: task

#104 Features: Scroll in Lobby view & Pop-up for inactive players
  package-lock.json
  package.json
  src/components/views/game/game/yourhand/YourHand.tsx
  src/components/views/lobby/Lobby.tsx
  src/styles/ui/Divs.scss
  src/styles/ui/Lists.scss
  src/styles/ui/images.scss
Labels: enhancement, help wanted

#111 Feature beta test hover fix
  public/favicon.ico
  public/index.html
  src/components/views/game/game/GameView.scss
  src/components/views/game/game/gametable/GameTable.scss
  src/components/views/game/game/scoreannouncing/AnnouncementModal.scss
  src/components/views/game/game/yourhand/YourHand.scss
Labels: task, beta testing

#135 some animation for the landing page --> you remember?
  src/components/views/createplayer/CreatePlayer.scss
  src/components/views/createplayer/CreatePlayer.tsx
  src/img/oberin.png
  src/styles/ui/Divs.scss
  src/styles/ui/images.scss
Labels: task, nice, frontend

#132 Update readme frontend
  README.md
  doc/img/eslint.png
  doc/img/mi.png
  doc/img/mobx.png
  doc/img/npm.png
  doc/img/react.png
  doc/img/tsx.png
  src/img/views_screeshots/Announcing_stage.png
  src/img/views_screeshots/Landing_page.png
  src/img/views_screeshots/Lobby.png
  src/img/views_screeshots/Loser_screen.png
  src/img/views_screeshots/Room.png
  src/img/views_screeshots/Round_with_one_card.png
  src/img/views_screeshots/Stacked_round.png
  src/img/views_screeshots/Standard_round.png
  src/img/views_screeshots/Winner_screen.png
Labels: task, nice, frontend
